server:
  port: 9999
  context-path: /MyLog
  jsp-servlet:
    init-parameters:
      development: true

spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/hadoop
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:com/baizhi/dao/*Mapper.xml